services:
  neo4j:
    image: neo4j:5.26.18-community-bullseye
    ports:
      - "7687:7687" # db
      - "7474:7474" # web
    environment:
      - NEO4J_AUTH=neo4j/123456789
    healthcheck:
      test: [ "CMD", "/var/lib/neo4j/bin/cypher-shell", "-u", "neo4j", "-p", "123456789", "MATCH () RETURN count(*) as count" ]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 20s
    restart: always
  matcher:
    depends_on:
      neo4j:
        condition: service_healthy
    image: gglamer/matcher:latest
    ports:
      - "50051:50051"
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=123456789
      - NEO4J_DATABASE=neo4j
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:9092
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
      - "9644:9644" # admin API

  console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    environment:
      KAFKA_BROKERS: redpanda:9092
      REDPANDA_ADMIN_API: http://redpanda:9644
    ports:
      - "8080:8080"
    depends_on:
      - redpanda
