from typing import Protocol
from uuid import UUID

from entity.form import Form
from entity.group import Group, GroupRequest
from entity.parameters import Parameters

# Если объект не найден делать raise NotFoundError - лежит в entity.errors
# Если нужна кастомная ошибка делать raise DomainError() и передавать в аргументы строку с ошибкой


class FormRepository(Protocol):
    def create(self, form: Form) -> UUID: ...
    def get_by_user_id(self, user_id: UUID) -> Form: ...
    def update_parameters_by_user_id(
        self, user_id: UUID, parameters: Parameters
    ) -> None: ...
    def delete_by_user_id(self, user_id: UUID) -> None: ...


class GroupRequestRepository(Protocol):
    def create(self, group_id: UUID, user_id: UUID) -> UUID: ...
    def get(self, request_id: UUID) -> GroupRequest: ...
    def get_all_by_group_id(self, group_id: UUID) -> list[GroupRequest]: ...
    def get_all_by_user_id(self, user_id: UUID) -> list[GroupRequest]: ...
    def delete(self, request_id: UUID) -> None: ...
    def delete_all_by_user_id(self, user_id: UUID) -> None: ...


class GroupRepository(Protocol):
    def create(self, group: Group) -> UUID: ...
    def get(self, group_id: UUID) -> Group: ...
    def get_by_user_id(self, user_id: UUID) -> Group: ...
    def get_by_owner_id(self, owner_id: UUID) -> Group: ...
    def get_all(self) -> list[tuple[UUID, tuple[UUID]]]: ...
    def update_parameters(self, group_id: UUID, parameters: Parameters) -> None: ...
    def delete(self, group_id: UUID) -> None: ...
    def delete_by_owner_id(self, owner_id: UUID) -> None: ...

    def list_members(self, group_id: UUID) -> list[Form]: ...
    def count_members(self, group_id: UUID) -> int: ...
    def add_user(self, user_id: UUID, group_id: UUID) -> None: ...
    def rm_user(self, user_id: UUID, group_id: UUID) -> None: ...
    def calculate_params(self, group_id: UUID) -> None: ...
    def change_owner(self, group_id: UUID, new_owner_id: UUID) -> None: ...


class GroupRecomendationRepository(Protocol):
    """Рекомендует группу другой группе"""

    def execute(self, group_id: UUID) -> list[tuple[Group, float]]:
        """
        Берёт среднюю из анкет пользователей, состоящих в группе
        и ищет ближайших из остальных групп, так же по средним из анкет
        """
        ...


class CacheGroupRecomendationRepository(Protocol):
    def execute(self, user_id: UUID) -> list[tuple[Group, float]]: ...
    def add(self, user_id: UUID, value: list[tuple[Group, float]]) -> None: ...
    def commit(self) -> None: ...


class NotificationRepository(Protocol):
    def send_join_request(
        self,
        group: Group,
        user_id: UUID,
    ) -> None: ...

    def accept_join_request(
        self,
        group: Group,
        request: GroupRequest,
    ) -> None: ...

    def reject_join_request(
        self,
        group: Group,
        request: GroupRequest,
    ) -> None: ...

    def kick(
        self,
        group: Group,
        user_id: UUID,
        remained: int,
    ) -> None: ...

    def leave(
        self,
        group: Group,
        user_id: UUID,
        remained: int,
    ) -> None: ...

    def flush(self) -> None: ...
