from typing import List, Optional, Protocol
from uuid import UUID

from entity.form import Form
from entity.group import Group


class FormRepository(Protocol):
    def create_form(self, form: Form) -> None: ...
    def get_form_by_user(self, user_id: UUID) -> Optional[Form]: ...
    def update_form(self, form: Form) -> None: ...
    def delete_form_by_user(self, user_id: UUID) -> None: ...


class GroupRepository(Protocol):
    def create_group(self, group: Group) -> None: ...
    def get_group(self, group_id: UUID) -> Group: ...
    def update_group(self, group: Group) -> None: ...
    def delete_group(self, group_id: UUID) -> None: ...
    def list_groups(self) -> List[Group]: ...
