from typing import Protocol
from uuid import UUID

from entity.form import Form
from entity.group import Group, GroupRequest
from entity.parameters import Parameters


class FormRepository(Protocol):
    def create(self, form: Form) -> UUID: ...
    def get_by_user_id(self, user_id: UUID) -> Form: ...
    def update_parameters_by_user_id(
        self, user_id: UUID, parameters: Parameters
    ) -> None: ...
    def delete_by_user_id(self, user_id: UUID) -> None: ...


class GroupRequestRepository(Protocol):
    def create(self, group_id: UUID, user_id: UUID) -> UUID: ...
    def get(self, request_id: UUID) -> GroupRequest: ...
    def get_all(self, group_id: UUID) -> list[GroupRequest]: ...
    def delete(self, request_id: UUID) -> None: ...


class GroupRepository(Protocol):
    def create(self, group: Group) -> UUID: ...
    def get(self, group_id: UUID) -> Group: ...
    def get_by_user_id(self, user_id: UUID) -> Group: ...
    def get_by_owner_id(self, owner_id: UUID) -> Group: ...
    def update_parameters(self, group_id: UUID, parameters: Parameters) -> None: ...
    def delete(self, group_id: UUID) -> None: ...
    def delete_by_owner_id(self, owner_id: UUID) -> None: ...

    def list_members(self, group_id: UUID) -> list[Form]: ...
    def count_members(self, group_id: UUID) -> int: ...
    def add_user(self, user_id: UUID, group_id: UUID) -> None: ...
    def rm_user(self, user_id: UUID, group_id: UUID) -> None: ...
    def calculate_params(self, group_id: UUID) -> None: ...
    def change_owner(self, group_id: UUID, new_owner_id: UUID) -> None: ...


class GroupRecomendationRepository(Protocol):
    """Рекомендует группу другой группе"""

    def execute(self, group_id: UUID) -> list[tuple[Group, float]]:
        """
        Берёт среднюю из анкет пользователей, состоящих в группе
        и ищет ближайших из остальных групп, так же по средним из анкет
        """
        ...


class NotificationRepository(Protocol):
    """Абстракция для отправки уведомлений пользователям"""

    def notify_owner_of_new_request(
        self,
        group_id: UUID,
        user_id: UUID,
    ) -> None:
        """Уведомить владельца группы о новом запросе на вступление."""

    def notify_user_of_decision(
        self,
        user_id: UUID,
        group_id: UUID,
        accepted: bool,
    ) -> None:
        """Уведомить пользователя о решении (принят или отклонен)"""
