from typing import Protocol

from entity.user import User


class UserRepositoryInterface(Protocol):
    def create(self, user: User) -> str: ...
    def get(self, id: str) -> User: ...
    def update(self, user: User) -> None: ...
    def delete(self, id: str) -> None: ...
